// Auto-generated combined styles index
import { StyleSheet } from "react-native";
import { styles as homeStyles } from "./home.js";
import { styles as modalStyles } from "./modal.js";
import { styles as playerStyles } from "./player.js";
import { styles as resultCardStyles } from "./result-card.js";
import { styles as sharedStyles } from "./shared.js";

const mergedStyles = Object.freeze({
  ...(typeof homeStyles.brand !== "undefined" ? { brand: homeStyles.brand } : {}),
  ...(typeof homeStyles.subtitle !== "undefined" ? { subtitle: homeStyles.subtitle } : {}),
  ...(typeof homeStyles.headerActions !== "undefined" ? { headerActions: homeStyles.headerActions } : {}),
  ...(typeof homeStyles.iconButton !== "undefined" ? { iconButton: homeStyles.iconButton } : {}),
  ...(typeof homeStyles.iconButtonText !== "undefined" ? { iconButtonText: homeStyles.iconButtonText } : {}),
  ...(typeof homeStyles.searchPanel !== "undefined" ? { searchPanel: homeStyles.searchPanel } : {}),
  ...(typeof homeStyles.searchInput !== "undefined" ? { searchInput: homeStyles.searchInput } : {}),
  ...(typeof homeStyles.searchButton !== "undefined" ? { searchButton: homeStyles.searchButton } : {}),
  ...(typeof homeStyles.searchButtonText !== "undefined" ? { searchButtonText: homeStyles.searchButtonText } : {}),
  ...(typeof homeStyles.statusRow !== "undefined" ? { statusRow: homeStyles.statusRow } : {}),
  ...(typeof homeStyles.statusText !== "undefined" ? { statusText: homeStyles.statusText } : {}),
  ...(typeof homeStyles.overlay !== "undefined" ? { overlay: homeStyles.overlay } : {}),
  ...(typeof homeStyles.overlayText !== "undefined" ? { overlayText: homeStyles.overlayText } : {}),
  ...(typeof modalStyles.modalBackdrop !== "undefined" ? { modalBackdrop: modalStyles.modalBackdrop } : {}),
  ...(typeof modalStyles.modalSheet !== "undefined" ? { modalSheet: modalStyles.modalSheet } : {}),
  ...(typeof modalStyles.modalHeader !== "undefined" ? { modalHeader: modalStyles.modalHeader } : {}),
  ...(typeof modalStyles.modalTitle !== "undefined" ? { modalTitle: modalStyles.modalTitle } : {}),
  ...(typeof modalStyles.closeText !== "undefined" ? { closeText: modalStyles.closeText } : {}),
  ...(typeof modalStyles.settingsActions !== "undefined" ? { settingsActions: modalStyles.settingsActions } : {}),
  ...(typeof modalStyles.smallButton !== "undefined" ? { smallButton: modalStyles.smallButton } : {}),
  ...(typeof modalStyles.smallButtonText !== "undefined" ? { smallButtonText: modalStyles.smallButtonText } : {}),
  ...(typeof modalStyles.sourceRow !== "undefined" ? { sourceRow: modalStyles.sourceRow } : {}),
  ...(typeof modalStyles.sourceInfo !== "undefined" ? { sourceInfo: modalStyles.sourceInfo } : {}),
  ...(typeof modalStyles.sourceRowActive !== "undefined" ? { sourceRowActive: modalStyles.sourceRowActive } : {}),
  ...(typeof modalStyles.sourceName !== "undefined" ? { sourceName: modalStyles.sourceName } : {}),
  ...(typeof modalStyles.sourceUrl !== "undefined" ? { sourceUrl: modalStyles.sourceUrl } : {}),
  ...(typeof modalStyles.sourceControls !== "undefined" ? { sourceControls: modalStyles.sourceControls } : {}),
  ...(typeof modalStyles.sourceCheck !== "undefined" ? { sourceCheck: modalStyles.sourceCheck } : {}),
  ...(typeof modalStyles.sourceCheckActive !== "undefined" ? { sourceCheckActive: modalStyles.sourceCheckActive } : {}),
  ...(typeof modalStyles.sourceActionText !== "undefined" ? { sourceActionText: modalStyles.sourceActionText } : {}),
  ...(typeof modalStyles.sourceDangerText !== "undefined" ? { sourceDangerText: modalStyles.sourceDangerText } : {}),
  ...(typeof modalStyles.sourceForm !== "undefined" ? { sourceForm: modalStyles.sourceForm } : {}),
  ...(typeof modalStyles.formTitle !== "undefined" ? { formTitle: modalStyles.formTitle } : {}),
  ...(typeof modalStyles.formInput !== "undefined" ? { formInput: modalStyles.formInput } : {}),
  ...(typeof modalStyles.formActions !== "undefined" ? { formActions: modalStyles.formActions } : {}),
  ...(typeof modalStyles.formButton !== "undefined" ? { formButton: modalStyles.formButton } : {}),
  ...(typeof modalStyles.primaryButton !== "undefined" ? { primaryButton: modalStyles.primaryButton } : {}),
  ...(typeof modalStyles.primaryButtonText !== "undefined" ? { primaryButtonText: modalStyles.primaryButtonText } : {}),
  ...(typeof modalStyles.historyRow !== "undefined" ? { historyRow: modalStyles.historyRow } : {}),
  ...(typeof modalStyles.clearButton !== "undefined" ? { clearButton: modalStyles.clearButton } : {}),
  ...(typeof modalStyles.clearButtonText !== "undefined" ? { clearButtonText: modalStyles.clearButtonText } : {}),
  ...(typeof playerStyles.playerHeader !== "undefined" ? { playerHeader: playerStyles.playerHeader } : {}),
  ...(typeof playerStyles.ghostButton !== "undefined" ? { ghostButton: playerStyles.ghostButton } : {}),
  ...(typeof playerStyles.ghostButtonText !== "undefined" ? { ghostButtonText: playerStyles.ghostButtonText } : {}),
  ...(typeof playerStyles.headerTitle !== "undefined" ? { headerTitle: playerStyles.headerTitle } : {}),
  ...(typeof playerStyles.video !== "undefined" ? { video: playerStyles.video } : {}),
  ...(typeof playerStyles.playerContent !== "undefined" ? { playerContent: playerStyles.playerContent } : {}),
  ...(typeof playerStyles.nowPlaying !== "undefined" ? { nowPlaying: playerStyles.nowPlaying } : {}),
  ...(typeof playerStyles.rateRow !== "undefined" ? { rateRow: playerStyles.rateRow } : {}),
  ...(typeof playerStyles.rateLabel !== "undefined" ? { rateLabel: playerStyles.rateLabel } : {}),
  ...(typeof playerStyles.rateButtons !== "undefined" ? { rateButtons: playerStyles.rateButtons } : {}),
  ...(typeof playerStyles.rateButton !== "undefined" ? { rateButton: playerStyles.rateButton } : {}),
  ...(typeof playerStyles.rateButtonActive !== "undefined" ? { rateButtonActive: playerStyles.rateButtonActive } : {}),
  ...(typeof playerStyles.rateButtonText !== "undefined" ? { rateButtonText: playerStyles.rateButtonText } : {}),
  ...(typeof playerStyles.rateButtonTextActive !== "undefined" ? { rateButtonTextActive: playerStyles.rateButtonTextActive } : {}),
  ...(typeof playerStyles.lineRow !== "undefined" ? { lineRow: playerStyles.lineRow } : {}),
  ...(typeof playerStyles.lineButton !== "undefined" ? { lineButton: playerStyles.lineButton } : {}),
  ...(typeof playerStyles.lineButtonActive !== "undefined" ? { lineButtonActive: playerStyles.lineButtonActive } : {}),
  ...(typeof playerStyles.lineButtonText !== "undefined" ? { lineButtonText: playerStyles.lineButtonText } : {}),
  ...(typeof playerStyles.lineButtonTextActive !== "undefined" ? { lineButtonTextActive: playerStyles.lineButtonTextActive } : {}),
  ...(typeof playerStyles.episodeGrid !== "undefined" ? { episodeGrid: playerStyles.episodeGrid } : {}),
  ...(typeof playerStyles.episodeButton !== "undefined" ? { episodeButton: playerStyles.episodeButton } : {}),
  ...(typeof playerStyles.episodeButtonActive !== "undefined" ? { episodeButtonActive: playerStyles.episodeButtonActive } : {}),
  ...(typeof playerStyles.episodeButtonText !== "undefined" ? { episodeButtonText: playerStyles.episodeButtonText } : {}),
  ...(typeof playerStyles.episodeButtonTextActive !== "undefined" ? { episodeButtonTextActive: playerStyles.episodeButtonTextActive } : {}),
  ...(typeof playerStyles.detailBlock !== "undefined" ? { detailBlock: playerStyles.detailBlock } : {}),
  ...(typeof playerStyles.sectionTitle !== "undefined" ? { sectionTitle: playerStyles.sectionTitle } : {}),
  ...(typeof playerStyles.description !== "undefined" ? { description: playerStyles.description } : {}),
  ...(typeof resultCardStyles.resultCard !== "undefined" ? { resultCard: resultCardStyles.resultCard } : {}),
  ...(typeof resultCardStyles.shadowOffset !== "undefined" ? { shadowOffset: resultCardStyles.shadowOffset } : {}),
  ...(typeof resultCardStyles.poster !== "undefined" ? { poster: resultCardStyles.poster } : {}),
  ...(typeof resultCardStyles.posterFallback !== "undefined" ? { posterFallback: resultCardStyles.posterFallback } : {}),
  ...(typeof resultCardStyles.posterFallbackText !== "undefined" ? { posterFallbackText: resultCardStyles.posterFallbackText } : {}),
  ...(typeof resultCardStyles.resultBody !== "undefined" ? { resultBody: resultCardStyles.resultBody } : {}),
  ...(typeof resultCardStyles.resultTitle !== "undefined" ? { resultTitle: resultCardStyles.resultTitle } : {}),
  ...(typeof resultCardStyles.resultType !== "undefined" ? { resultType: resultCardStyles.resultType } : {}),
  ...(typeof sharedStyles.safeArea !== "undefined" ? { safeArea: sharedStyles.safeArea } : {}),
  ...(typeof sharedStyles.header !== "undefined" ? { header: sharedStyles.header } : {}),
  ...(typeof sharedStyles.listContent !== "undefined" ? { listContent: sharedStyles.listContent } : {}),
  ...(typeof sharedStyles.centerState !== "undefined" ? { centerState: sharedStyles.centerState } : {}),
  ...(typeof sharedStyles.centerTitle !== "undefined" ? { centerTitle: sharedStyles.centerTitle } : {}),
  ...(typeof sharedStyles.centerText !== "undefined" ? { centerText: sharedStyles.centerText } : {}),
  ...(typeof sharedStyles.resultMeta !== "undefined" ? { resultMeta: sharedStyles.resultMeta } : {}),
  ...(typeof sharedStyles.ghostButton !== "undefined" ? { ghostButton: sharedStyles.ghostButton } : {}),
  ...(typeof sharedStyles.ghostButtonText !== "undefined" ? { ghostButtonText: sharedStyles.ghostButtonText } : {}),
});

export const styles = mergedStyles;
